//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 01:49:18 PM BST 
//


package org.kie.simulation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A command parameter
 * 
 * <p>Java class for CommandArgumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommandArgumentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="argumentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="argumentData" type="{http://org.kie.simulation/types/}CommonXMLDataWrapperType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommandArgumentType", propOrder = {
    "argumentName",
    "argumentData"
})
public class CommandArgumentType {

    @XmlElement(required = true)
    protected String argumentName;
    @XmlElement(required = true)
    protected CommonXMLDataWrapperType argumentData;

    /**
     * Gets the value of the argumentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArgumentName() {
        return argumentName;
    }

    /**
     * Sets the value of the argumentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArgumentName(String value) {
        this.argumentName = value;
    }

    /**
     * Gets the value of the argumentData property.
     * 
     * @return
     *     possible object is
     *     {@link CommonXMLDataWrapperType }
     *     
     */
    public CommonXMLDataWrapperType getArgumentData() {
        return argumentData;
    }

    /**
     * Sets the value of the argumentData property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonXMLDataWrapperType }
     *     
     */
    public void setArgumentData(CommonXMLDataWrapperType value) {
        this.argumentData = value;
    }

}
