//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.21 at 01:49:18 PM BST 
//


package org.kie.simulation;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.kie.simulation package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.kie.simulation
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScenarioSimulationResponse }
     * 
     */
    public ScenarioSimulationResponse createScenarioSimulationResponse() {
        return new ScenarioSimulationResponse();
    }

    /**
     * Create an instance of {@link ScenarioSimulationResponseType }
     * 
     */
    public ScenarioSimulationResponseType createScenarioSimulationResponseType() {
        return new ScenarioSimulationResponseType();
    }

    /**
     * Create an instance of {@link ScenarioSimulationRequest }
     * 
     */
    public ScenarioSimulationRequest createScenarioSimulationRequest() {
        return new ScenarioSimulationRequest();
    }

    /**
     * Create an instance of {@link ScenarioSimulationRequestType }
     * 
     */
    public ScenarioSimulationRequestType createScenarioSimulationRequestType() {
        return new ScenarioSimulationRequestType();
    }

    /**
     * Create an instance of {@link ScenarioRequestType }
     * 
     */
    public ScenarioRequestType createScenarioRequestType() {
        return new ScenarioRequestType();
    }

    /**
     * Create an instance of {@link CommandArgumentType }
     * 
     */
    public CommandArgumentType createCommandArgumentType() {
        return new CommandArgumentType();
    }

    /**
     * Create an instance of {@link StackItem }
     * 
     */
    public StackItem createStackItem() {
        return new StackItem();
    }

    /**
     * Create an instance of {@link CommonXMLDataWrapperType }
     * 
     */
    public CommonXMLDataWrapperType createCommonXMLDataWrapperType() {
        return new CommonXMLDataWrapperType();
    }

}
